settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: apexitconsult.com
    name: apexitconsult.com
    url: 'https://apexitconsult.com/'

  - id: blog.fsxmarket.com
    name: blog.fsxmarket.com
    url: 'https://blog.fsxmarket.com'

  - id: offertool.thebazaarinc.com
    name: offertool.thebazaarinc.com
    url: 'https://offertool.thebazaarinc.com/'

  - id: files.elkerp.com
    name: files.elkerp.com
    url: 'https://files.elkerp.com/'

  - id: media.fsxmarket.com
    name: media.fsxmarket.com
    url: 'https://media.fsxmarket.com/'

  - id: o2cool.com
    name: o2cool.com
    url: 'https://o2cool.com/'

  - id: trevahome.com
    name: trevahome.com
    url: 'http://trevahome.com/'

  - id: waterbobble.com
    name: waterbobble.com
    url: 'http://waterbobble.com/'

  - id: b2b.o2cool.com
    name: b2b.o2cool.com
    url: 'http://b2b.o2cool.com/'


  - id: lunchbots.com
    name: lunchbots.com
    url: 'http://lunchbots.com/'

    
